### ISSUE TITLE
Including the `@nrwl/react/typings/image.d.ts` typings breaks React TypeScript builds

### ISSUE THREAD

**Issue by chiubaka** [chiubaka/genesis#130]
Encountered while working on #123.

Errors look like this:
```
shinsoku:genesis-lib-e2e dchiu$ nx build react-app --verbose

> nx run react-app:build:production

assets by status 364 KiB [cached] 7 assets
Entrypoint main = runtime.57061bc4509fbeb8.esm.js main.0f74571d7ab342b8.esm.js
Entrypoint polyfills = runtime.57061bc4509fbeb8.esm.js polyfills.f349bbd464fc4530.esm.js
Entrypoint styles = runtime.57061bc4509fbeb8.esm.js styles.ef46db3751d8e999.css
  

ERROR in ./packages/react-app/src/main.tsx:1:28
TS1149: File name '/users/dchiu/developer/genesis/tmp/nx-e2e/genesis-lib-e2e/node_modules/@types/react/index.d.ts' differs from already included file name '/Users/dchiu/Developer/genesis/tmp/nx-e2e/genesis-lib-e2e/node_modules/@types/react/index.d.ts' only in casing.
  The file is in the program because:
    Type library referenced via 'react' from file '/Users/dchiu/Developer/genesis/tmp/nx-e2e/genesis-lib-e2e/node_modules/@nrwl/react/typings/image.d.ts'
    Imported via 'react' from file '/Users/dchiu/Developer/genesis/tmp/nx-e2e/genesis-lib-e2e/node_modules/@types/react-dom/index.d.ts' with packageId '@types/react/index.d.ts@18.0.18'
    Imported via 'react' from file '/Users/dchiu/Developer/genesis/tmp/nx-e2e/genesis-lib-e2e/node_modules/@nrwl/react/typings/image.d.ts' with packageId '@types/react/index.d.ts@18.0.18'
    Imported via './' from file '/users/dchiu/developer/genesis/tmp/nx-e2e/genesis-lib-e2e/node_modules/@types/react/jsx-runtime.d.ts' with packageId '@types/react/index.d.ts@18.0.18'
    Imported via "react" from file '/Users/dchiu/Developer/genesis/tmp/nx-e2e/genesis-lib-e2e/packages/react-app/src/main.tsx' with packageId '@types/react/index.d.ts@18.0.18'
    Imported via 'react' from file '/users/dchiu/developer/genesis/tmp/nx-e2e/genesis-lib-e2e/node_modules/@types/react-dom/client.d.ts' with packageId '@types/react/index.d.ts@18.0.18'
    Imported via "react" from file '/Users/dchiu/Developer/genesis/tmp/nx-e2e/genesis-lib-e2e/node_modules/react-router-dom/index.d.ts' with packageId '@types/react/index.d.ts@18.0.18'
    Imported via "react" from file '/Users/dchiu/Developer/genesis/tmp/nx-e2e/genesis-lib-e2e/node_modules/react-router/lib/components.d.ts' with packageId '@types/react/index.d.ts@18.0.18'
    Imported via "react" from file '/Users/dchiu/Developer/genesis/tmp/nx-e2e/genesis-lib-e2e/node_modules/react-router/lib/context.d.ts' with packageId '@types/react/index.d.ts@18.0.18'
    Imported via "react" from file '/Users/dchiu/Developer/genesis/tmp/nx-e2e/genesis-lib-e2e/node_modules/react-router/lib/hooks.d.ts' with packageId '@types/react/index.d.ts@18.0.18'
    Entry point for implicit type library 'react' with packageId '@types/react/index.d.ts@18.0.18'
    Imported via 'react' from file '/Users/dchiu/Developer/genesis/tmp/nx-e2e/genesis-lib-e2e/node_modules/@types/react-router/index.d.ts' with packageId '@types/react/index.d.ts@18.0.18'
    Imported via 'react' from file '/Users/dchiu/Developer/genesis/tmp/nx-e2e/genesis-lib-e2e/node_modules/@types/react-router-dom/index.d.ts' with packageId '@types/react/index.d.ts@18.0.18'
  > 1 | import { StrictMode } from "react";
      |                            ^^^^^^^
    2 | import * as ReactDOM from "react-dom/client";
    3 | import { BrowserRouter } from "react-router-dom";
    4 |

webpack 5.74.0 compiled with 1 error (a4139eb9a52f39bc)

 >  NX   ENOENT: no such file or directory, open 'dist/packages/react-app/index.html'


Error: ENOENT: no such file or directory, open 'dist/packages/react-app/index.html'
    at Object.openSync (node:fs:599:3)
    at writeFileSync (node:fs:2221:35)
    at /Users/dchiu/Developer/genesis/tmp/nx-e2e/genesis-lib-e2e/node_modules/@nrwl/web/src/utils/webpack/write-index-html.js:211:32
    at Generator.next (<anonymous>)
    at /Users/dchiu/Developer/genesis/tmp/nx-e2e/genesis-lib-e2e/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/dchiu/Developer/genesis/tmp/nx-e2e/genesis-lib-e2e/node_modules/tslib/tslib.js:114:16)
    at writeIndexHtml (/Users/dchiu/Developer/genesis/tmp/nx-e2e/genesis-lib-e2e/node_modules/@nrwl/web/src/utils/webpack/write-index-html.js:192:20)
    at /Users/dchiu/Developer/genesis/tmp/nx-e2e/genesis-lib-e2e/node_modules/@nrwl/web/src/executors/webpack/webpack.impl.js:118:61
    at Generator.next (<anonymous>)

 ————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Running target "react-app:build" failed
```

Incorrect casing occurs between `/users/dchiu/developer` and `/Users/dchiu/Developer`.

Removing [this line](https://github.com/nrwl/nx/blob/master/packages/react/typings/image.d.ts#L1) from the `image.d.ts` file appears to resolve the issue.

It's unclear why some version of `react` is being imported with the wrong casing and unclear if this will affect other things in the future. However, the image typings provided by `image.d.ts` are mostly useless, so I'm just not including those typings for now.

**Comment by chiubaka** [comment]
Bumping this so that it doesn't appear stale for import into Linear.
