### ISSUE TITLE
New bare run of `genesis` crashes with ESLint error on commit

### ISSUE THREAD

**Issue by chiubaka** [chiubaka/genesis#167]
```
added 1109 packages, and audited 1110 packages in 56s

125 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

>  NX  Generating @chiubaka/nx-plugin:preset

Generating @chiubaka/nx-plugin workspace preset with options:
{
  "_": [
    "chiubaka",
    "quick",
    "experiment",
    "to",
    "test",
    "the",
    "behavior",
    "of",
    "Webpack",
    "tree",
    "shaking",
    "Object]"
  ],
  "preset": "@chiubaka/nx-plugin",
  "nxCloud": false,
  "directory": "webpack-tree-shaking",
  "workspaceName": "webpack-tree-shaking",
  "workspaceScope": "chiubaka",
  "skipGit": true,
  "g": true,
  "skipGitHub": true,
  "description": "A",
  "allPrompts": false,
  "a": false,
  "commit": "[object",
  "/bin/sh": "/Users/dchiu/.npm/_npx/baa7532e5a3bd827/node_modules/.bin/create-nx-workspace",
  "name": "chiubaka",
  "appName": "",
  "packageManager": "npm",
  "defaultBase": "master",
  "ci": "",
  "cli": "nx",
  "style": "css",
  "skipInstall": false,
  "linter": "eslint",
  "presetVersion": "undefined",
  "disableImmutableInstalls": false
}
Modifying workspace layout to conform to e2e/ and packages/
Adding standard scripts to package.json
Generating base TsConfig file
Generating linting setup with options:
{"packageManager":"yarn"}
Generating ESLint setup with options:
{
  "packageManager": "yarn"
}
Copying .eslintrc.json template
Adding linting scripts to package.json for yarn
Generating Prettier setup
Updating .prettierrc
Generating lint-staged setup
Copying .lintstagedrc.yml template
Adding lint-staged scripts to package.json
Generating test setup
Generating Jest setup
Copying Jest configuration templates
Updating .gitignore
Generating Codecov setup
Copying Codecov config template
Generating CI setup
Generating CircleCI setup
Copying .circleci config templates
Generating README.md with options:
{
  "_": [
    "chiubaka",
    "quick",
    "experiment",
    "to",
    "test",
    "the",
    "behavior",
    "of",
    "Webpack",
    "tree",
    "shaking",
    "Object]"
  ],
  "preset": "@chiubaka/nx-plugin",
  "nxCloud": false,
  "directory": "webpack-tree-shaking",
  "workspaceName": "webpack-tree-shaking",
  "workspaceScope": "chiubaka",
  "skipGit": true,
  "g": true,
  "skipGitHub": true,
  "description": "A",
  "allPrompts": false,
  "a": false,
  "commit": "[object",
  "/bin/sh": "/Users/dchiu/.npm/_npx/baa7532e5a3bd827/node_modules/.bin/create-nx-workspace",
  "name": "chiubaka",
  "appName": "",
  "packageManager": "npm",
  "defaultBase": "master",
  "ci": "",
  "cli": "nx",
  "style": "css",
  "skipInstall": false,
  "linter": "eslint",
  "presetVersion": "undefined",
  "disableImmutableInstalls": false
}
Copying README.md template
Generating git repo with options:
{
  "commitMessage": "Initial commit with files generated by @chiubaka/nx-plugin@0.2.0 preset.",
  "preCommitCommand": "yarn lint:staged",
  "prePushCommand": "nx affected --target=test",
  "organization": "chiubaka",
  "repositoryName": "webpack-tree-shaking",
  "repositoryDescription": "A",
  "privateRepository": true,
  "enableCircleCiStatusChecks": true,
  "enableCodecovStatusChecks": true,
  "skipGitHub": true
}
Generating git hooks setup
UPDATE nx.json
UPDATE package.json
DELETE apps
DELETE libs
CREATE e2e/.gitkeep
CREATE packages/.gitkeep
DELETE package-lock.json
CREATE .yarnrc.yml
UPDATE tsconfig.base.json
CREATE .eslintrc.json
UPDATE .prettierrc
CREATE .lintstagedrc.yml
CREATE jest.config.ts
CREATE jest.preset.js
UPDATE .gitignore
CREATE codecov.yml
CREATE .circleci/config.yml
CREATE README.md
Running post-processing tasks for preset generator
Reinstalling packages with yarn
Running post-processing tasks for TSConfig generator
Installing new dependencies for TSConfig generator
➤ YN0000: ┌ Resolution step
➤ YN0002: │ @nrwl/cypress@npm:15.2.4 [bc771] doesn't provide nx (pc72ec), requested by @nrwl/devkit
➤ YN0002: │ @nrwl/cypress@npm:15.2.4 [bc771] doesn't provide typescript (p9a2bf), requested by @phenomnomnominal/tsquery
➤ YN0002: │ @nrwl/cypress@npm:15.2.4 [bc771] doesn't provide typescript (pcefb6), requested by fork-ts-checker-webpack-plugin
➤ YN0002: │ @nrwl/cypress@npm:15.2.4 [bc771] doesn't provide typescript (pc080f), requested by ts-loader
➤ YN0002: │ @nrwl/devkit@npm:15.2.4 [0f23b] doesn't provide typescript (p78315), requested by @phenomnomnominal/tsquery
➤ YN0002: │ @nrwl/devkit@npm:15.2.4 [5ae9a] doesn't provide typescript (p7b856), requested by @phenomnomnominal/tsquery
➤ YN0002: │ @nrwl/eslint-plugin-nx@npm:15.2.4 [fed21] doesn't provide eslint (p71145), requested by @typescript-eslint/utils
➤ YN0002: │ @nrwl/eslint-plugin-nx@npm:15.2.4 [fed21] doesn't provide nx (p818d6), requested by @nrwl/devkit
➤ YN0002: │ @nrwl/jest@npm:15.2.4 doesn't provide nx (p53bb0), requested by @nrwl/devkit
➤ YN0002: │ @nrwl/jest@npm:15.2.4 doesn't provide typescript (p57f72), requested by @phenomnomnominal/tsquery
➤ YN0002: │ @nrwl/js@npm:15.2.4 doesn't provide nx (p76bdc), requested by @nrwl/devkit
➤ YN0002: │ @nrwl/linter@npm:15.2.4 [be794] doesn't provide typescript (p61391), requested by @phenomnomnominal/tsquery
➤ YN0002: │ @nrwl/node@npm:15.2.4 doesn't provide nx (p019f6), requested by @nrwl/devkit
➤ YN0002: │ @nrwl/nx-plugin@npm:15.2.4 doesn't provide nx (p33ecc), requested by @nrwl/devkit
➤ YN0002: │ @nrwl/react@npm:15.2.4 doesn't provide nx (paea92), requested by @nrwl/devkit
➤ YN0002: │ @nrwl/react@npm:15.2.4 doesn't provide typescript (p8efe9), requested by @phenomnomnominal/tsquery
➤ YN0002: │ @nrwl/rollup@npm:15.2.4 doesn't provide @babel/core (pbb8d9), requested by @rollup/plugin-babel
➤ YN0002: │ @nrwl/rollup@npm:15.2.4 doesn't provide nx (p07b0e), requested by @nrwl/devkit
➤ YN0002: │ @nrwl/rollup@npm:15.2.4 doesn't provide typescript (pe4890), requested by rollup-plugin-typescript2
➤ YN0002: │ @nrwl/storybook@npm:15.2.4 doesn't provide nx (pb7225), requested by @nrwl/devkit
➤ YN0002: │ @nrwl/web@npm:15.2.4 doesn't provide nx (p595f1), requested by @nrwl/devkit
➤ YN0002: │ @nrwl/webpack@npm:15.2.4 doesn't provide @babel/core (p72490), requested by babel-loader
➤ YN0002: │ @nrwl/webpack@npm:15.2.4 doesn't provide @types/node (pdf1d1), requested by ts-node
➤ YN0002: │ @nrwl/webpack@npm:15.2.4 doesn't provide nx (p8e370), requested by @nrwl/devkit
➤ YN0002: │ @nrwl/webpack@npm:15.2.4 doesn't provide typescript (pc85be), requested by fork-ts-checker-webpack-plugin
➤ YN0002: │ @nrwl/webpack@npm:15.2.4 doesn't provide typescript (pb71ac), requested by ts-loader
➤ YN0002: │ @nrwl/webpack@npm:15.2.4 doesn't provide typescript (p9c1c1), requested by ts-node
➤ YN0002: │ chiubaka@workspace:. doesn't provide @typescript-eslint/parser (pd61cd), requested by @nrwl/eslint-plugin-nx
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 0s 367ms
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 0s 388ms
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed in 0s 487ms
➤ YN0000: Done with warnings in 1s 418ms
Running post-processing tasks for ESLint generator
Installing new dependencies for ESLint generator
Running lint fix over all files
Running post-processing tasks for Prettier generator
Installing new dependencies for Prettier generator
Running post-processing tasks for lint-staged generator
Installing new dependencies for lint-staged generator
Runing post-processing tasks for testing generator
Running post-processing tasks for Jest generator
Installing new dependencies for Jest generator
Running post-processing tasks for git generator
Initializing git repo in /Users/dchiu/Developer/webpack-tree-shaking
Running post-processing tasks for git hooks generator
Installing new dependencies for git hooks generator
Running prepare script to finish git hooks setup
Installing pre-commit hook
Installing pre-push hook
Creating initial commit with message "Initial commit with files generated by @chiubaka/nx-plugin@0.2.0 preset."

 >  NX   Command failed: git commit -m "Initial commit with files generated by @chiubaka/nx-plugin@0.2.0 preset."

   ⚠ Skipping backup because there’s no initial commit yet.
   
   [STARTED] Preparing lint-staged...
   [SUCCESS] Preparing lint-staged...
   [STARTED] Running tasks for staged files...
   [STARTED] .lintstagedrc.yml — 649 files (chunk 1/2)...
   [STARTED] .lintstagedrc.yml — 649 files (chunk 2/2)...
   [STARTED] *.(js|jsx|ts|tsx|yml|yaml|json) — 4 files
   [STARTED] *.(js|jsx|ts|tsx|yml|yaml|json) — 8 files
   [STARTED] prettier --write
   [STARTED] prettier --write
   [SUCCESS] prettier --write
   [STARTED] eslint --fix --quiet
   [SUCCESS] prettier --write
   [STARTED] eslint --fix --quiet
   [FAILED] eslint --fix --quiet [FAILED]
   [FAILED] eslint --fix --quiet [FAILED]
   [FAILED] eslint --fix --quiet [FAILED]
   [STARTED] Applying modifications from tasks...
   [SUCCESS] Applying modifications from tasks...
   
   ✖ eslint --fix --quiet:
   
   Oops! Something went wrong! :(
   
   ESLint: 8.41.0
   
   TypeError: Cannot read properties of undefined (reading 'getAllComments')
   Occurred while linting /Users/dchiu/Developer/webpack-tree-shaking/.eslintrc.json:1
   Rule: "unicorn/expiring-todo-comments"
       at Object.Program (/Users/dchiu/Developer/webpack-tree-shaking/node_modules/eslint/lib/rules/no-warning-comments.js:193:45)
       at Program (/Users/dchiu/Developer/webpack-tree-shaking/node_modules/eslint-plugin-unicorn/rules/expiring-todo-comments.js:511:10)
       at /Users/dchiu/Developer/webpack-tree-shaking/node_modules/eslint-plugin-unicorn/rules/utils/rule.js:39:18
       at ruleErrorHandler (/Users/dchiu/Developer/webpack-tree-shaking/node_modules/eslint/lib/linter/linter.js:1050:28)
       at /Users/dchiu/Developer/webpack-tree-shaking/node_modules/eslint/lib/linter/safe-emitter.js:45:58
       at Array.forEach (<anonymous>)
       at Object.emit (/Users/dchiu/Developer/webpack-tree-shaking/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
       at NodeEventGenerator.applySelector (/Users/dchiu/Developer/webpack-tree-shaking/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
       at NodeEventGenerator.applySelectors (/Users/dchiu/Developer/webpack-tree-shaking/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
       at NodeEventGenerator.enterNode (/Users/dchiu/Developer/webpack-tree-shaking/node_modules/eslint/lib/linter/node-event-generator.js:340:14)
   [FAILED] eslint --fix --quiet [KILLED]
   [FAILED] eslint --fix --quiet [KILLED]
   [FAILED] eslint --fix --quiet [KILLED]
   husky - pre-commit hook exited with code 1 (error)
   

Error: Command failed: git commit -m "Initial commit with files generated by @chiubaka/nx-plugin@0.2.0 preset."
⚠ Skipping backup because there’s no initial commit yet.

[STARTED] Preparing lint-staged...
[SUCCESS] Preparing lint-staged...
[STARTED] Running tasks for staged files...
[STARTED] .lintstagedrc.yml — 649 files (chunk 1/2)...
[STARTED] .lintstagedrc.yml — 649 files (chunk 2/2)...
[STARTED] *.(js|jsx|ts|tsx|yml|yaml|json) — 4 files
[STARTED] *.(js|jsx|ts|tsx|yml|yaml|json) — 8 files
[STARTED] prettier --write
[STARTED] prettier --write
[SUCCESS] prettier --write
[STARTED] eslint --fix --quiet
[SUCCESS] prettier --write
[STARTED] eslint --fix --quiet
[FAILED] eslint --fix --quiet [FAILED]
[FAILED] eslint --fix --quiet [FAILED]
[FAILED] eslint --fix --quiet [FAILED]
[STARTED] Applying modifications from tasks...
[SUCCESS] Applying modifications from tasks...

✖ eslint --fix --quiet:

Oops! Something went wrong! :(

ESLint: 8.41.0

TypeError: Cannot read properties of undefined (reading 'getAllComments')
Occurred while linting /Users/dchiu/Developer/webpack-tree-shaking/.eslintrc.json:1
Rule: "unicorn/expiring-todo-comments"
    at Object.Program (/Users/dchiu/Developer/webpack-tree-shaking/node_modules/eslint/lib/rules/no-warning-comments.js:193:45)
    at Program (/Users/dchiu/Developer/webpack-tree-shaking/node_modules/eslint-plugin-unicorn/rules/expiring-todo-comments.js:511:10)
    at /Users/dchiu/Developer/webpack-tree-shaking/node_modules/eslint-plugin-unicorn/rules/utils/rule.js:39:18
    at ruleErrorHandler (/Users/dchiu/Developer/webpack-tree-shaking/node_modules/eslint/lib/linter/linter.js:1050:28)
    at /Users/dchiu/Developer/webpack-tree-shaking/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/dchiu/Developer/webpack-tree-shaking/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/Users/dchiu/Developer/webpack-tree-shaking/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (/Users/dchiu/Developer/webpack-tree-shaking/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (/Users/dchiu/Developer/webpack-tree-shaking/node_modules/eslint/lib/linter/node-event-generator.js:340:14)
[FAILED] eslint --fix --quiet [KILLED]
[FAILED] eslint --fix --quiet [KILLED]
[FAILED] eslint --fix --quiet [KILLED]
husky - pre-commit hook exited with code 1 (error)

    at ChildProcess.exithandler (node:child_process:402:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)

 >  NX   Workspace creation failed, see above.

   Pass --verbose to see the stacktrace.


npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm WARN deprecated source-map-resolve@0.6.0: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
```

**Comment by chiubaka** [comment]
This prevented me from using `genesis` to handle project creation for a client, and also for creating a playground to mess with Webpack.

**Comment by chiubaka** [comment]
Seems like a problem with `eslint-plugin-unicorn`. A newly generated workspace has `43.0.2` installed through `@chiubaka/eslint-config`.

**Comment by chiubaka** [comment]
Problem also seems to be in the `unicorn/expiring-todo-comments` rule, particularly when running on a JSON file. Seems to me like `unicorn` shouldn't be enabled on JSON files at all...

**Comment by chiubaka** [comment]
Seems like there was a potential fix for this [here](https://github.com/sindresorhus/eslint-plugin-unicorn/issues/2117).

**Comment by chiubaka** [comment]
Looks like this is fixed with the release of `@chiubaka/eslint-config` v0.5.1!
